# Generated by Django 5.0.4 on 2024-04-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerreservation',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registerreservation'),
        ),
    ]
